# Generated by Django 4.2.3 on 2024-10-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToolBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='template_name',
            field=models.CharField(default='pages/tool_detail.html', max_length=100),
        ),
    ]
