# Generated by Django 5.2.7 on 2026-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeBoard', '0002_collection_variants_and_guided_valuation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='kind',
            field=models.CharField(choices=[('CARD', 'Carte'), ('SEALED', 'Scelle')], max_length=10),
        ),
        migrations.AlterField(
            model_name='collectiblevaluation',
            name='kind',
            field=models.CharField(choices=[('CARD', 'Carte'), ('SEALED', 'Scelle')], max_length=10),
        ),
    ]
