# Generated by Django 4.2.3 on 2024-11-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Arome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=40)),
                ("famille_aromatique", models.CharField(max_length=30)),
                ("sous_famille_aromatique", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Boisson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("categorie", models.CharField(max_length=100)),
                ("annee", models.IntegerField()),
                ("histoire", models.TextField()),
                ("Pays", models.CharField(max_length=20)),
                ("Region", models.CharField(max_length=20)),
                ("caracteristiques", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="Degustation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.JSONField()),
                ("commentaire", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("commentaires", models.JSONField()),
                (
                    "boisson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DrunkBoard.boisson",
                    ),
                ),
            ],
        ),
    ]
