# Generated by Django 4.2.3 on 2024-11-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnement',
            name='frequence_personnalisee',
            field=models.IntegerField(blank=True, help_text="Nombre de jours entre chaque paiement (nécessaire si 'Personnalisé' est sélectionné)", null=True),
        ),
        migrations.AddField(
            model_name='revenu',
            name='frequence_personnalisee',
            field=models.IntegerField(blank=True, help_text="Nombre de jours entre chaque paiement (nécessaire si 'Personnalisé' est sélectionné)", null=True),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='frequence',
            field=models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel'), ('PERSONALIZED', 'Personnalisé')], max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_asset',
            field=models.CharField(choices=[('STOCK', 'Action'), ('CRYPTO', 'Cryptomonnaie'), ('ETF', 'Fonds négocié en bourse'), ('FOREX', 'Paire de devises'), ('OBLIGATION', 'Obligation')], max_length=10),
        ),
        migrations.AlterField(
            model_name='revenu',
            name='frequence',
            field=models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel'), ('PERSONALIZED', 'Personnalisé')], max_length=20),
        ),
    ]
