# Generated by Django 6.1.1 on 2026-09-04 17:34

import FundBoard.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('MANUAL_CREATE', 'Création manuelle'), ('MANUAL_UPDATE', 'Modification manuelle'), ('MANUAL_ARCHIVE', 'Archivage manuel'), ('IMPORT', 'Import'), ('IMPORT_ROLLBACK', "Annulation d'import"), ('EXPORT', 'Export')], max_length=30)),
                ('object_type', models.CharField(blank=True, max_length=50)),
                ('object_pk', models.PositiveBigIntegerField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_format', models.CharField(choices=[('JSON', 'JSON'), ('XLSX', 'Excel (.xlsx)')], max_length=10)),
                ('schema_version', models.CharField(max_length=20)),
                ('file_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('COMPLETED', 'Terminé'), ('PARTIAL', 'Partiel'), ('FAILED', 'Échec'), ('ROLLED_BACK', 'Annulé')], default='RUNNING', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rolled_back_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=50)),
                ('row_number', models.PositiveIntegerField()),
                ('model_name', models.CharField(max_length=50)),
                ('object_pk', models.PositiveBigIntegerField()),
                ('action', models.CharField(choices=[('CREATED', 'Création'), ('UPDATED', 'Mise à jour')], max_length=10)),
                ('before_data', models.JSONField(blank=True, default=dict)),
                ('after_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=50)),
                ('row_number', models.PositiveIntegerField()),
                ('column', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('value_preview', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['sheet', 'row_number', 'column', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('loan_type', models.CharField(choices=[('AMORT_FIXED', 'Amortissable à taux fixe'), ('VARIABLE', 'Taux variable'), ('INTEREST_ONLY', 'In fine'), ('CONSUMER', 'Crédit à la consommation'), ('OTHER', 'Autre')], default='AMORT_FIXED', max_length=20)),
                ('currency', models.CharField(default='EUR', max_length=3, validators=[FundBoard.validators.validate_currency_code])),
                ('original_principal', models.DecimalField(decimal_places=8, max_digits=30)),
                ('outstanding_principal', models.DecimalField(decimal_places=8, max_digits=30)),
                ('nominal_rate', models.DecimalField(decimal_places=6, help_text='Taux nominal annuel en pourcentage.', max_digits=9)),
                ('apr', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('duration_months', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ('insurance_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('insurance_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('initial_fees', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('deferred_months', models.PositiveIntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['archived', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PrivateEquityHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('company_or_fund', models.CharField(max_length=255)),
                ('vintage_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3, validators=[FundBoard.validators.validate_currency_code])),
                ('commitment', models.DecimalField(decimal_places=8, max_digits=30)),
                ('called_capital', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('distributions', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('net_asset_value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('valuation_date', models.DateField()),
                ('ownership_share', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5)),
                ('archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['archived', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_reference', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Appartement'), ('HOUSE', 'Maison'), ('LAND', 'Terrain'), ('SCPI', 'SCPI'), ('COMMERCIAL', 'Local commercial'), ('OTHER', 'Autre')], max_length=20)),
                ('address', models.TextField(blank=True)),
                ('surface_sqm', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ownership_share', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3, validators=[FundBoard.validators.validate_currency_code])),
                ('purchase_price', models.DecimalField(decimal_places=8, max_digits=30)),
                ('purchase_costs', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('renovation_costs', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('estimated_value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('valuation_date', models.DateField()),
                ('valuation_source', models.CharField(default='manual', max_length=100)),
                ('monthly_rent', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('monthly_charges', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('annual_property_tax', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=30)),
                ('archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['archived', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RealEstateValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('valuation_date', models.DateField()),
                ('source', models.CharField(default='manual', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-valuation_date'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='manual_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='manual_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='instrument',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Vide pour un référentiel partagé, renseigné pour un instrument privé.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='private_instruments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instrument',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archivée')], default='ACTIVE', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('manual_reference', ''), _negated=True), fields=('user', 'manual_reference'), name='uniq_account_user_manual_ref'),
        ),
        migrations.AddConstraint(
            model_name='instrument',
            constraint=models.UniqueConstraint(condition=models.Q(('owner__isnull', False), models.Q(('manual_reference', ''), _negated=True)), fields=('owner', 'manual_reference'), name='uniq_instrument_owner_manual_ref'),
        ),
        migrations.AddField(
            model_name='financialauditevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importchange',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='FundBoard.importbatch'),
        ),
        migrations.AddField(
            model_name='importissue',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='FundBoard.importbatch'),
        ),
        migrations.AddField(
            model_name='loan',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='FundBoard.account'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='privateequityholding',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_equity_holdings', to='FundBoard.account'),
        ),
        migrations.AddField(
            model_name='privateequityholding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_equity_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestate',
            name='linked_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='FundBoard.loan'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='realestatevaluation',
            name='real_estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='FundBoard.realestate'),
        ),
        migrations.AddIndex(
            model_name='financialauditevent',
            index=models.Index(fields=['user', '-created_at'], name='audit_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='importbatch',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ROLLED_BACK'), _negated=True), fields=('user', 'file_sha256'), name='uniq_import_batch_user_sha256'),
        ),
        migrations.AddConstraint(
            model_name='importchange',
            constraint=models.UniqueConstraint(fields=('batch', 'model_name', 'object_pk'), name='uniq_import_change_object'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['user', 'archived'], name='loan_user_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('user', 'manual_reference'), name='uniq_loan_user_manual_ref'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('original_principal__gt', 0)), name='loan_original_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_principal__gte', 0)), name='loan_outstanding_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('nominal_rate__gte', 0)), name='loan_rate_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('duration_months__gt', 0)), name='loan_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_principal__lte', models.F('original_principal'))), name='loan_outstanding_lte_original'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('initial_fees__gte', 0)), name='loan_fees_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('insurance_amount__gte', 0)), name='loan_insurance_positive'),
        ),
        migrations.AddConstraint(
            model_name='privateequityholding',
            constraint=models.UniqueConstraint(fields=('user', 'manual_reference'), name='uniq_privateequity_user_manual_ref'),
        ),
        migrations.AddConstraint(
            model_name='privateequityholding',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_share__gt', 0), ('ownership_share__lte', 100)), name='privateequity_valid_ownership_share'),
        ),
        migrations.AddConstraint(
            model_name='privateequityholding',
            constraint=models.CheckConstraint(condition=models.Q(('commitment__gte', 0)), name='pe_commitment_positive'),
        ),
        migrations.AddConstraint(
            model_name='privateequityholding',
            constraint=models.CheckConstraint(condition=models.Q(('called_capital__gte', 0)), name='pe_called_positive'),
        ),
        migrations.AddConstraint(
            model_name='privateequityholding',
            constraint=models.CheckConstraint(condition=models.Q(('distributions__gte', 0)), name='pe_distributions_positive'),
        ),
        migrations.AddConstraint(
            model_name='privateequityholding',
            constraint=models.CheckConstraint(condition=models.Q(('net_asset_value__gte', 0)), name='pe_nav_positive'),
        ),
        migrations.AddIndex(
            model_name='realestate',
            index=models.Index(fields=['user', 'archived'], name='realestate_user_archived_idx'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.UniqueConstraint(fields=('user', 'manual_reference'), name='uniq_realestate_user_manual_ref'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('ownership_share__gt', 0), ('ownership_share__lte', 100)), name='realestate_valid_ownership_share'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='realestate_purchase_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_value__gte', 0)), name='realestate_value_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('surface_sqm__isnull', True), ('surface_sqm__gt', 0), _connector='OR'), name='realestate_surface_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_costs__gte', 0)), name='realestate_costs_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('renovation_costs__gte', 0)), name='realestate_renovation_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_rent__gte', 0)), name='realestate_rent_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('monthly_charges__gte', 0)), name='realestate_charges_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestate',
            constraint=models.CheckConstraint(condition=models.Q(('annual_property_tax__gte', 0)), name='realestate_tax_positive'),
        ),
        migrations.AddConstraint(
            model_name='realestatevaluation',
            constraint=models.UniqueConstraint(fields=('real_estate', 'valuation_date', 'source'), name='uniq_realestate_valuation_date_source'),
        ),
        migrations.AddConstraint(
            model_name='realestatevaluation',
            constraint=models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='realestate_valuation_positive'),
        ),
    ]
