# Generated by Django 4.2.3 on 2025-05-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0002_abonnement_frequence_personnalisee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='api_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='api_service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
