# Generated by Django 6.1.1 on 2026-09-04 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0002_financialauditevent_importbatch_importchange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='market_state',
            field=models.CharField(choices=[('PRE', 'Préouverture'), ('REGULAR', 'Séance'), ('POST', 'Après séance'), ('CLOSED', 'Marché fermé'), ('UNKNOWN', 'Inconnu')], default='UNKNOWN', max_length=10),
        ),
        migrations.AddField(
            model_name='price',
            name='market_timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='financialauditevent',
            name='event_type',
            field=models.CharField(choices=[('MANUAL_CREATE', 'Création manuelle'), ('MANUAL_UPDATE', 'Modification manuelle'), ('MANUAL_ARCHIVE', 'Archivage manuel'), ('IMPORT', 'Import'), ('IMPORT_ROLLBACK', "Annulation d'import"), ('EXPORT', 'Export'), ('MARKET_REFRESH', 'Actualisation de cours'), ('FX_REFRESH', 'Actualisation du change'), ('SNAPSHOT', 'Snapshot patrimonial'), ('SETTINGS_UPDATE', 'Préférences de marché')], max_length=30),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instrument_type',
            field=models.CharField(choices=[('STOCK', 'Action'), ('ETF', 'ETF'), ('FUND', 'Fonds'), ('INDEX', 'Indice'), ('BOND', 'Obligation'), ('CRYPTO', 'Cryptomonnaie'), ('CURRENCY', 'Devise'), ('COMMODITY', 'Matière première'), ('PRIVATE_EQ', 'Private equity'), ('OTHER', 'Autre')], max_length=20),
        ),
        migrations.CreateModel(
            name='MarketDataPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_currency', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('USD', 'Dollar américain (USD)')], default='EUR', max_length=3)),
                ('equity_display_currency', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('USD', 'Dollar américain (USD)')], default='EUR', max_length=3)),
                ('crypto_display_currency', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('USD', 'Dollar américain (USD)')], default='USD', max_length=3)),
                ('benchmark_symbol', models.CharField(default='^STOXX50E', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('benchmark_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmark_preferences', to='FundBoard.instrument')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_data_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketDataStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('PENDING', 'Jamais synchronisé'), ('FRESH', 'À jour'), ('STALE', 'Périmé'), ('ERROR', 'En erreur')], default='PENDING', max_length=10)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('last_succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('last_price_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data_statuses', to='FundBoard.instrument')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_data_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state', 'instrument__name'],
                'indexes': [models.Index(fields=['user', 'state'], name='market_user_state_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'instrument', 'provider'), name='uniq_market_status_user_instrument_provider')],
            },
        ),
    ]
