# Generated by Django 4.2.3 on 2025-05-23 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0003_investmentaccount_api_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comptebancaire',
            name='type_compte',
            field=models.CharField(choices=[('CURRENT', 'Compte courant'), ('SAVINGS', 'Livret / Épargne'), ('CTO', 'Compte Titres Ordinaire'), ('PEA', 'Plan d’Épargne en Actions'), ('CRYPTO', 'Portefeuille Crypto'), ('OTHER', 'Autre')], default='CURRENT', max_length=10),
        ),
        migrations.AlterField(
            model_name='comptebancaire',
            name='devise',
            field=models.CharField(default='EUR', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='comptebancaire',
            name='solde',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15),
        ),
    ]
