# Generated by Django 6.1.1 on 2026-09-05 09:26

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("FundBoard", "0003_price_market_state_price_market_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="configuration",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuration non secrète du connecteur.",
            ),
        ),
        migrations.AddField(
            model_name="connection",
            name="consent_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="connection",
            name="last_tested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="financialauditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("MANUAL_CREATE", "Création manuelle"),
                    ("MANUAL_UPDATE", "Modification manuelle"),
                    ("MANUAL_ARCHIVE", "Archivage manuel"),
                    ("IMPORT", "Import"),
                    ("IMPORT_ROLLBACK", "Annulation d'import"),
                    ("EXPORT", "Export"),
                    ("MARKET_REFRESH", "Actualisation de cours"),
                    ("FX_REFRESH", "Actualisation du change"),
                    ("SNAPSHOT", "Snapshot patrimonial"),
                    ("SETTINGS_UPDATE", "Préférences de marché"),
                    ("CONNECTOR_CREATE", "Création de connexion"),
                    ("CONNECTOR_TEST", "Test de connexion"),
                    ("CONNECTOR_SYNC", "Synchronisation de connexion"),
                    ("CONNECTOR_DISCONNECT", "Déconnexion"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ConnectorSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manuelle"),
                            ("SCHEDULED", "Planifiée"),
                            ("IMPORT", "Import de fichier"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En cours"),
                            ("SUCCEEDED", "Réussie"),
                            ("PARTIAL", "Partielle"),
                            ("FAILED", "Échouée"),
                        ],
                        default="RUNNING",
                        max_length=20,
                    ),
                ),
                ("initial_sync", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("received_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("public_message", models.CharField(blank=True, max_length=255)),
                ("cursor_before", models.JSONField(blank=True, default=dict)),
                ("cursor_after", models.JSONField(blank=True, default=dict)),
                (
                    "correlation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="FundBoard.connection",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["connection", "-started_at"],
                        name="sync_conn_started_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "RUNNING")),
                        fields=("connection",),
                        name="uniq_running_sync_per_connection",
                    )
                ],
            },
        ),
    ]
