# Generated by Django 6.1.1 on 2026-09-05 09:50

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_phase_seven_histories(apps, schema_editor):
    Loan = apps.get_model("FundBoard", "Loan")
    LoanBalanceSnapshot = apps.get_model("FundBoard", "LoanBalanceSnapshot")
    PrivateEquityHolding = apps.get_model("FundBoard", "PrivateEquityHolding")
    PrivateEquityValuation = apps.get_model("FundBoard", "PrivateEquityValuation")
    RealEstate = apps.get_model("FundBoard", "RealEstate")
    RealEstateValuation = apps.get_model("FundBoard", "RealEstateValuation")
    for loan in Loan.objects.all().iterator():
        LoanBalanceSnapshot.objects.get_or_create(
            loan=loan,
            observed_on=loan.balance_date,
            source="phase7-initial",
            defaults={"outstanding_principal": loan.outstanding_principal},
        )
    for holding in PrivateEquityHolding.objects.all().iterator():
        PrivateEquityValuation.objects.get_or_create(
            holding=holding,
            valuation_date=holding.valuation_date,
            source="phase7-initial",
            defaults={
                "net_asset_value": holding.net_asset_value,
                "called_capital": holding.called_capital,
                "distributions": holding.distributions,
            },
        )
    for property_asset in RealEstate.objects.all().iterator():
        if not RealEstateValuation.objects.filter(real_estate=property_asset).exists():
            RealEstateValuation.objects.create(
                real_estate=property_asset,
                value=property_asset.estimated_value,
                valuation_date=property_asset.valuation_date,
                source="phase7-initial",
            )


def unseed_phase_seven_histories(apps, schema_editor):
    apps.get_model("FundBoard", "LoanBalanceSnapshot").objects.filter(
        source="phase7-initial"
    ).delete()
    apps.get_model("FundBoard", "PrivateEquityValuation").objects.filter(
        source="phase7-initial"
    ).delete()
    apps.get_model("FundBoard", "RealEstateValuation").objects.filter(
        source="phase7-initial"
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("FundBoard", "0004_connection_configuration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoanBalanceSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("outstanding_principal", models.DecimalField(decimal_places=8, max_digits=30)),
                ("observed_on", models.DateField()),
                ("source", models.CharField(default="manual", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-observed_on", "-pk"]},
        ),
        migrations.CreateModel(
            name="PrivateEquityValuation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("net_asset_value", models.DecimalField(decimal_places=8, max_digits=30)),
                ("called_capital", models.DecimalField(decimal_places=8, max_digits=30)),
                ("distributions", models.DecimalField(decimal_places=8, max_digits=30)),
                ("valuation_date", models.DateField()),
                ("source", models.CharField(default="manual", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-valuation_date", "-pk"]},
        ),
        migrations.AddField(
            model_name="loan",
            name="balance_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Date d'observation du capital restant dû.",
            ),
        ),
        migrations.AddField(
            model_name="privateequityholding",
            name="valuation_source",
            field=models.CharField(default="manual", max_length=100),
        ),
        migrations.AddField(
            model_name="realestate",
            name="annual_insurance",
            field=models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30),
        ),
        migrations.AddField(
            model_name="realestate",
            name="annual_other_costs",
            field=models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30),
        ),
        migrations.AddField(
            model_name="realestate",
            name="vacancy_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Hypothèse annuelle de vacance locative, en pourcentage.",
                max_digits=5,
            ),
        ),
        migrations.AddConstraint(
            model_name="privateequityholding",
            constraint=models.CheckConstraint(
                condition=models.Q(("called_capital__lte", models.F("commitment"))),
                name="pe_called_lte_commitment",
            ),
        ),
        migrations.AddConstraint(
            model_name="realestate",
            constraint=models.CheckConstraint(
                condition=models.Q(("annual_insurance__gte", 0)),
                name="realestate_insurance_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="realestate",
            constraint=models.CheckConstraint(
                condition=models.Q(("annual_other_costs__gte", 0)),
                name="realestate_other_costs_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="realestate",
            constraint=models.CheckConstraint(
                condition=models.Q(("vacancy_rate__gte", 0), ("vacancy_rate__lte", 100)),
                name="realestate_vacancy_rate_valid",
            ),
        ),
        migrations.AddField(
            model_name="loanbalancesnapshot",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balance_snapshots",
                to="FundBoard.loan",
            ),
        ),
        migrations.AddField(
            model_name="privateequityvaluation",
            name="holding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="valuations",
                to="FundBoard.privateequityholding",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanbalancesnapshot",
            constraint=models.UniqueConstraint(
                fields=("loan", "observed_on", "source"),
                name="uniq_loan_balance_date_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="loanbalancesnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("outstanding_principal__gte", 0)),
                name="loan_snapshot_balance_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="privateequityvaluation",
            constraint=models.UniqueConstraint(
                fields=("holding", "valuation_date", "source"),
                name="uniq_pe_valuation_date_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="privateequityvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("net_asset_value__gte", 0)),
                name="pe_val_nav_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="privateequityvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("called_capital__gte", 0)),
                name="pe_val_called_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="privateequityvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(("distributions__gte", 0)),
                name="pe_val_dist_positive",
            ),
        ),
        migrations.RunPython(seed_phase_seven_histories, unseed_phase_seven_histories),
    ]
