# Generated by Django 4.2.3 on 2025-05-23 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FundBoard', '0004_comptebancaire_type_compte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('CURRENT', 'Compte courant'), ('SAVINGS', 'Livret / Épargne'), ('CTO', 'Compte Titres Ordinaire'), ('PEA', 'Plan d’Épargne en Actions'), ('CRYPTO', 'Portefeuille Crypto'), ('OTHER', 'Autre')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('api_service', models.CharField(blank=True, max_length=50, null=True)),
                ('api_connected', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='FundBoard.account')),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('freq', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel'), ('PERSONALIZED', 'Personnalisé')], max_length=20)),
                ('freq_custom', models.IntegerField(blank=True, null=True)),
                ('next_payday', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('freq', models.CharField(choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel'), ('PERSONALIZED', 'Personnalisé')], max_length=20)),
                ('freq_custom', models.IntegerField(blank=True, help_text="Si 'Personnalisé', nombre de jours entre chaque paiement", null=True)),
                ('next_due', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='SuiviAsset',
            new_name='WatchAsset',
        ),
        migrations.RenameModel(
            old_name='ListeSuivi',
            new_name='Watchlist',
        ),
        migrations.RemoveField(
            model_name='abonnement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comptebancaire',
            name='user',
        ),
        migrations.DeleteModel(
            name='Devise',
        ),
        migrations.RemoveField(
            model_name='dividende',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='dividende',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historiquesolde',
            name='compte_bancaire',
        ),
        migrations.RemoveField(
            model_name='investmentaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revenu',
            name='user',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='secteur',
            new_name='sector',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='date_creation',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='lu',
            new_name='read',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='valeur_fermeture',
            new_name='close_price',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='valeur_basse',
            new_name='high_price',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='valeur_haute',
            new_name='low_price',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='valeur_ouverture',
            new_name='open_price',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='volume_echange',
            new_name='volume',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='montant',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date_transaction',
            new_name='date_trx',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='quantite',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='type_transaction',
            new_name='trx_type',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='prix_unitaire',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='watchasset',
            old_name='liste_suivi',
            new_name='watchlist',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='nom',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='compte_bancaire',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='investment_account',
        ),
        migrations.AlterField(
            model_name='asset',
            name='type_asset',
            field=models.CharField(choices=[('STOCK', 'Action'), ('CRYPTO', 'Cryptomonnaie'), ('ETF', 'ETF'), ('FOREX', 'Forex'), ('OBLIGATION', 'Obligation')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Abonnement',
        ),
        migrations.DeleteModel(
            name='CompteBancaire',
        ),
        migrations.DeleteModel(
            name='Dividende',
        ),
        migrations.DeleteModel(
            name='HistoriqueSolde',
        ),
        migrations.DeleteModel(
            name='InvestmentAccount',
        ),
        migrations.DeleteModel(
            name='Revenu',
        ),
        migrations.AddField(
            model_name='dividend',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundBoard.asset'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='FundBoard.account'),
            preserve_default=False,
        ),
    ]
