# Generated by Django 4.2.3 on 2025-08-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0005_account_balancehistory_dividend_income_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='other_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
