# Generated by Django 6.1.1 on 2026-09-05 10:08

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import FundBoard.validators


class Migration(migrations.Migration):
    dependencies = [
        ("FundBoard", "0005_loanbalancesnapshot_privateequityvaluation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompoundInterestScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(default="EUR", max_length=3, validators=[FundBoard.validators.validate_currency_code])),
                ("initial_capital", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30)),
                ("periodic_contribution", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30)),
                ("contribution_frequency", models.CharField(choices=[("MONTHLY", "Mensuelle"), ("QUARTERLY", "Trimestrielle"), ("SEMIANNUAL", "Semestrielle"), ("ANNUAL", "Annuelle")], default="MONTHLY", max_length=12)),
                ("contribution_timing", models.CharField(choices=[("BEGIN", "Début de période"), ("END", "Fin de période")], default="END", max_length=8)),
                ("duration_years", models.PositiveSmallIntegerField(default=20)),
                ("annual_return", models.DecimalField(decimal_places=6, default=Decimal("5"), max_digits=9)),
                ("annual_fees", models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=9)),
                ("annual_inflation", models.DecimalField(decimal_places=6, default=Decimal("2"), max_digits=9)),
                ("tax_mode", models.CharField(choices=[("NONE", "Aucune fiscalité"), ("FINAL_GAINS", "Taux unique sur les gains finaux")], default="NONE", max_length=12)),
                ("tax_rate", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7)),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="compound_interest_scenarios", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["archived", "name", "pk"],
                "indexes": [models.Index(fields=["user", "archived"], name="compound_user_archived_idx")],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("initial_capital__gte", 0)), name="compound_sim_initial_positive"),
                    models.CheckConstraint(condition=models.Q(("periodic_contribution__gte", 0)), name="compound_sim_contribution_positive"),
                    models.CheckConstraint(condition=models.Q(("duration_years__gte", 1), ("duration_years__lte", 100)), name="compound_sim_duration_valid"),
                    models.CheckConstraint(condition=models.Q(("annual_return__gt", -100)), name="compound_sim_return_valid"),
                    models.CheckConstraint(condition=models.Q(("annual_fees__gte", 0), ("annual_fees__lte", 100)), name="compound_sim_fees_valid"),
                    models.CheckConstraint(condition=models.Q(("annual_inflation__gte", 0)), name="compound_sim_inflation_positive"),
                    models.CheckConstraint(condition=models.Q(("tax_rate__gte", 0), ("tax_rate__lte", 100)), name="compound_sim_tax_valid"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanSimulationScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("currency", models.CharField(default="EUR", max_length=3, validators=[FundBoard.validators.validate_currency_code])),
                ("principal", models.DecimalField(decimal_places=8, max_digits=30)),
                ("annual_rate", models.DecimalField(decimal_places=6, max_digits=9)),
                ("calculation_mode", models.CharField(choices=[("PAYMENT", "Calculer la mensualité"), ("DURATION", "Calculer la durée")], default="PAYMENT", max_length=10)),
                ("duration_months", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("target_payment", models.DecimalField(blank=True, decimal_places=8, max_digits=30, null=True)),
                ("insurance_mode", models.CharField(choices=[("FIXED", "Montant mensuel fixe"), ("PERCENT", "Pourcentage annuel")], default="FIXED", max_length=10)),
                ("insurance_value", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30)),
                ("insurance_basis", models.CharField(choices=[("INITIAL", "Capital initial"), ("OUTSTANDING", "Capital restant dû")], default="INITIAL", max_length=12)),
                ("initial_fees", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30)),
                ("deferment_months", models.PositiveSmallIntegerField(default=0)),
                ("deferment_type", models.CharField(choices=[("NONE", "Aucun"), ("PARTIAL", "Partiel — intérêts payés"), ("TOTAL", "Total — intérêts capitalisés")], default="NONE", max_length=10)),
                ("one_off_prepayment", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30)),
                ("one_off_prepayment_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("recurring_prepayment", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=30)),
                ("recurring_prepayment_start_month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("start_date", models.DateField(default=django.utils.timezone.localdate)),
                ("archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="loan_simulation_scenarios", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["archived", "name", "pk"],
                "indexes": [models.Index(fields=["user", "archived"], name="loan_sim_user_archived_idx")],
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("principal__gt", 0)), name="loan_sim_principal_positive"),
                    models.CheckConstraint(condition=models.Q(("annual_rate__gte", 0)), name="loan_sim_rate_positive"),
                    models.CheckConstraint(condition=models.Q(("duration_months__isnull", True), models.Q(("duration_months__gte", 1), ("duration_months__lte", 1200)), _connector="OR"), name="loan_sim_duration_valid"),
                    models.CheckConstraint(condition=models.Q(("target_payment__isnull", True), ("target_payment__gt", 0), _connector="OR"), name="loan_sim_payment_positive"),
                    models.CheckConstraint(condition=models.Q(("insurance_value__gte", 0)), name="loan_sim_insurance_positive"),
                    models.CheckConstraint(condition=models.Q(("initial_fees__gte", 0)), name="loan_sim_fees_positive"),
                    models.CheckConstraint(condition=models.Q(("deferment_months__lte", 1199)), name="loan_sim_deferment_valid"),
                    models.CheckConstraint(condition=models.Q(("one_off_prepayment__gte", 0)), name="loan_sim_oneoff_positive"),
                    models.CheckConstraint(condition=models.Q(("recurring_prepayment__gte", 0)), name="loan_sim_recurring_positive"),
                ],
            },
        ),
    ]
