# Generated by Django 4.2.3 on 2025-08-13 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FundBoard', '0006_transaction_other_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_recurring', models.BooleanField(default=True)),
                ('freq', models.CharField(blank=True, choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel'), ('PERSONALIZED', 'Personnalisé')], max_length=20, null=True)),
                ('freq_custom', models.IntegerField(blank=True, help_text="If 'PERSONALIZED', number of days between payments.", null=True)),
                ('next_due', models.DateField()),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FundBoard.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-next_due', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.CreateModel(
            name='OneTimeExpense',
            fields=[
            ],
            options={
                'verbose_name': 'One-time expense',
                'verbose_name_plural': 'One-time expenses',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('FundBoard.expense',),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'is_recurring', 'next_due'], name='FundBoard_e_user_id_64adbd_idx'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('FundBoard.expense',),
        ),
    ]
