# Generated by Django 4.2.3 on 2025-08-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0007_expense_delete_subscription_onetimeexpense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancehistory',
            name='account',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='dividend',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchasset',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='watchasset',
            name='watchlist',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='OneTimeExpense',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name'], 'verbose_name': 'Compte', 'verbose_name_plural': 'Comptes'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['next_due']},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['next_payday']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_trx']},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='FundBoard_e_user_id_64adbd_idx',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='close_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='high_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='low_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='pricehistory',
            old_name='open_price',
            new_name='open',
        ),
        migrations.RemoveField(
            model_name='account',
            name='api_connected',
        ),
        migrations.RemoveField(
            model_name='account',
            name='api_service',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type_asset',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='other_details',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Action'), ('CRYPTO', 'Cryptomonnaie'), ('ETF', 'ETF'), ('FOREX', 'Forex'), ('BOND', 'Obligation')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('CURRENT', 'Compte courant'), ('SAVINGS', 'Livret / Épargne'), ('CTO', 'Compte Titres Ordinaire'), ('PEA', 'Plan d’Épargne en Actions'), ('CRYPTO', 'Portefeuille Crypto'), ('OTHER', 'Autre')], default='CURRENT', max_length=12),
        ),
        migrations.AlterField(
            model_name='expense',
            name='freq_custom',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de jours si personnalisé', null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='freq_custom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FundBoard.account'),
        ),
        migrations.DeleteModel(
            name='BalanceHistory',
        ),
        migrations.DeleteModel(
            name='Dividend',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='WatchAsset',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
