# Generated by Django 4.2.3 on 2025-08-13 14:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FundBoard', '0009_income_is_recurring_alter_income_freq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('avg_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundBoard.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundBoard.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['account__name', 'asset__ticker'],
                'unique_together': {('user', 'account', 'asset')},
            },
        ),
    ]
