# Generated by Django 4.2.3 on 2025-08-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0010_holding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'name'], name='FundBoard_a_user_id_e50bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'next_due'], name='FundBoard_e_user_id_25dd92_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'is_recurring'], name='FundBoard_e_user_id_bf8555_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user', 'tag'], name='FundBoard_e_user_id_a618f2_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['user', 'account', 'asset'], name='FundBoard_h_user_id_73e428_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'next_payday'], name='FundBoard_i_user_id_cfcf0a_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user', 'is_recurring'], name='FundBoard_i_user_id_004b75_idx'),
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['asset', 'date'], name='FundBoard_p_asset_i_d0a20f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-date_trx'], name='FundBoard_t_user_id_2e9c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'trx_type'], name='FundBoard_t_user_id_e51a4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('freq__isnull', True), ('freq_custom__isnull', True), ('is_recurring', False)), models.Q(('freq__isnull', False), ('is_recurring', True)), _connector='OR'), name='expense_recurring_freq_consistency'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('freq__isnull', True), ('freq_custom__isnull', True), ('is_recurring', False)), models.Q(('freq__isnull', False), ('is_recurring', True)), _connector='OR'), name='income_recurring_freq_consistency'),
        ),
    ]
