# Generated by Django 4.2.3 on 2025-11-11 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0011_account_fundboard_a_user_id_e50bc3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date de fin pour les dépenses récurrentes (optionnel)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='income',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date de fin pour les revenus récurrents (optionnel)', null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='income',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
