# Generated by Django 4.2.3 on 2026-02-26 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0012_expense_end_date_expense_start_date_income_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FundBoard.account'),
        ),
        migrations.AddField(
            model_name='income',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
