# Generated by Django 5.2.7 on 2026-03-04 18:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def migrate_legacy_data(apps, schema_editor):
    Account = apps.get_model("FundBoard", "Account")
    Asset = apps.get_model("FundBoard", "Asset")
    Transaction = apps.get_model("FundBoard", "Transaction")
    Leg = apps.get_model("FundBoard", "Leg")
    Expense = apps.get_model("FundBoard", "Expense")
    Income = apps.get_model("FundBoard", "Income")
    CashflowRule = apps.get_model("FundBoard", "CashflowRule")

    tolerance = Decimal("0.01")

    def get_fiat(currency: str):
        ticker = (currency or "EUR").upper()
        obj, _ = Asset.objects.get_or_create(
            ticker=ticker,
            defaults={"name": ticker, "asset_type": "FIAT", "precision": 8},
        )
        return obj

    # 1) Rules migration (Expense/Income -> CashflowRule)
    for exp in Expense.objects.all():
        CashflowRule.objects.get_or_create(
            user_id=exp.user_id,
            kind="EXPENSE",
            name=exp.name,
            amount=exp.amount or Decimal("0"),
            start_date=exp.start_date,
            end_date=exp.end_date,
            next_due=exp.next_due,
            defaults={
                "is_recurring": exp.is_recurring,
                "freq": exp.freq,
                "freq_custom": exp.freq_custom,
                "default_account_id": exp.account_id,
                "tag": exp.tag,
                "notes": exp.notes,
            },
        )

    for inc in Income.objects.all():
        CashflowRule.objects.get_or_create(
            user_id=inc.user_id,
            kind="INCOME",
            name=inc.name,
            amount=inc.amount or Decimal("0"),
            start_date=inc.start_date,
            end_date=inc.end_date,
            next_due=inc.next_payday,
            defaults={
                "is_recurring": inc.is_recurring,
                "freq": inc.freq,
                "freq_custom": inc.freq_custom,
                "default_account_id": inc.account_id,
                "tag": inc.tag,
                "notes": inc.notes,
            },
        )

    # 2) Opening transactions from legacy account balance
    for account in Account.objects.all():
        legacy_balance = getattr(account, "balance", Decimal("0")) or Decimal("0")
        if legacy_balance == 0:
            continue
        fiat = get_fiat(getattr(account, "currency", None) or getattr(account, "base_currency", "EUR"))
        trx = Transaction.objects.create(
            user_id=account.user_id,
            trx_type="OPENING",
            date_trx=timezone.now(),
            account_id=account.id,
            asset_id=fiat.id,
            amount=legacy_balance,
            quantity=abs(legacy_balance),
            unit_price=Decimal("1"),
            memo="Opening balance migration",
            executed_at=timezone.now(),
            description="Opening balance migration",
            integrity_delta=Decimal("0"),
            tolerance_applied=tolerance,
            is_balanced=True,
        )
        Leg.objects.create(
            transaction_id=trx.id,
            account_id=account.id,
            asset_id=fiat.id,
            quantity=legacy_balance,
            value_reference=legacy_balance,
            reference_currency=fiat.ticker,
        )

    # 3) Legacy transaction -> legs conversion
    for tx in Transaction.objects.all():
        if Leg.objects.filter(transaction_id=tx.id).exists():
            continue

        tx.executed_at = tx.date_trx
        tx.description = tx.memo
        tx.tolerance_applied = tolerance

        account_id = tx.account_id
        if not account_id:
            tx.is_balanced = False
            tx.integrity_delta = abs(tx.amount or Decimal("0"))
            tx.save(update_fields=["executed_at", "description", "tolerance_applied", "is_balanced", "integrity_delta"])
            continue

        account = Account.objects.filter(id=account_id).first()
        ref_currency = (
            getattr(account, "base_currency", None)
            or getattr(account, "currency", None)
            or "EUR"
        )
        fiat = get_fiat(ref_currency)

        created_values = []
        amount = tx.amount or Decimal("0")
        qty = tx.quantity or Decimal("0")
        unit_price = tx.unit_price or Decimal("0")

        if tx.trx_type in ("DEPOSIT", "WITHDRAWAL"):
            created_values.append(amount)
            Leg.objects.create(
                transaction_id=tx.id,
                account_id=account_id,
                asset_id=fiat.id,
                quantity=amount,
                value_reference=amount,
                reference_currency=ref_currency,
            )
        elif tx.trx_type == "BUY":
            gross = abs(qty * unit_price) if qty and unit_price else abs(amount)
            fee = max(Decimal("0"), abs(amount) - gross)
            created_values.extend([amount, gross])
            Leg.objects.create(
                transaction_id=tx.id,
                account_id=account_id,
                asset_id=fiat.id,
                quantity=amount,
                value_reference=amount,
                reference_currency=ref_currency,
            )
            if tx.asset_id:
                Leg.objects.create(
                    transaction_id=tx.id,
                    account_id=account_id,
                    asset_id=tx.asset_id,
                    quantity=qty or Decimal("0.000000000001"),
                    unit_price_reference=unit_price if unit_price else None,
                    value_reference=gross,
                    reference_currency=ref_currency,
                )
            if fee > 0:
                created_values.append(-fee)
                Leg.objects.create(
                    transaction_id=tx.id,
                    account_id=account_id,
                    asset_id=fiat.id,
                    quantity=-fee,
                    value_reference=-fee,
                    reference_currency=ref_currency,
                    is_fee=True,
                )
        elif tx.trx_type == "SELL":
            gross = abs(qty * unit_price) if qty and unit_price else abs(amount)
            fee = max(Decimal("0"), gross - abs(amount))
            created_values.extend([-gross, abs(amount)])
            if tx.asset_id:
                Leg.objects.create(
                    transaction_id=tx.id,
                    account_id=account_id,
                    asset_id=tx.asset_id,
                    quantity=-(qty or Decimal("0.000000000001")),
                    unit_price_reference=unit_price if unit_price else None,
                    value_reference=-gross,
                    reference_currency=ref_currency,
                )
            Leg.objects.create(
                transaction_id=tx.id,
                account_id=account_id,
                asset_id=fiat.id,
                quantity=abs(amount),
                value_reference=abs(amount),
                reference_currency=ref_currency,
            )
            if fee > 0:
                created_values.append(-fee)
                Leg.objects.create(
                    transaction_id=tx.id,
                    account_id=account_id,
                    asset_id=fiat.id,
                    quantity=-fee,
                    value_reference=-fee,
                    reference_currency=ref_currency,
                    is_fee=True,
                )
        else:
            created_values.append(amount)
            Leg.objects.create(
                transaction_id=tx.id,
                account_id=account_id,
                asset_id=fiat.id,
                quantity=amount,
                value_reference=amount,
                reference_currency=ref_currency,
            )

        delta = abs(sum(created_values, Decimal("0")))
        tx.integrity_delta = delta
        tx.is_balanced = delta <= tolerance
        tx.save(update_fields=["executed_at", "description", "tolerance_applied", "is_balanced", "integrity_delta"])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('FundBoard', '0013_income_account_income_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INCOME', 'Revenu'), ('EXPENSE', 'Depense')], max_length=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_due', models.DateField()),
                ('freq', models.CharField(blank=True, choices=[('DAILY', 'Quotidien'), ('WEEKLY', 'Hebdomadaire'), ('MONTHLY', 'Mensuel'), ('YEARLY', 'Annuel'), ('PERSONALIZED', 'Personnalise')], max_length=20, null=True)),
                ('freq_custom', models.PositiveIntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=12, max_digits=30)),
                ('unit_price_reference', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True)),
                ('value_reference', models.DecimalField(decimal_places=12, max_digits=30)),
                ('reference_currency', models.CharField(default='EUR', max_length=10)),
                ('is_fee', models.BooleanField(default=False)),
                ('is_adjustment', models.BooleanField(default=False)),
                ('adjustment_type', models.CharField(blank=True, choices=[('ROUNDING', 'Rounding'), ('FX_SLIPPAGE', 'FX slippage'), ('SYSTEM_CORRECTION', 'System correction')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['ticker']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-executed_at']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='FundBoard_t_user_id_2e9c3e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='holding',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account',
            name='base_currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='asset',
            name='precision',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='holding',
            name='avg_cost_reference',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='last_computed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='reference_currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='reference_currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='executed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='integrity_delta',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_balanced',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tolerance_applied',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('CURRENT', 'Compte courant'), ('SAVINGS', 'Livret / Epargne'), ('CTO', 'Compte Titres Ordinaire'), ('PEA', "Plan d'Epargne en Actions"), ('CRYPTO', 'Portefeuille Crypto'), ('OTHER', 'Autre')], default='CURRENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('STOCK', 'Action'), ('CRYPTO', 'Cryptomonnaie'), ('ETF', 'ETF'), ('FOREX', 'Forex'), ('BOND', 'Obligation'), ('FIAT', 'Monnaie fiduciaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='quantity',
            field=models.DecimalField(decimal_places=12, default=Decimal('0'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='close',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='high',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='low',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='open',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trx_type',
            field=models.CharField(choices=[('OPENING', 'Ouverture'), ('DEPOSIT', 'Depot'), ('WITHDRAWAL', 'Retrait'), ('BUY', 'Achat'), ('SELL', 'Vente'), ('TRANSFER', 'Transfert'), ('CONVERSION', 'Conversion'), ('STAKING', 'Staking')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-executed_at'], name='FundBoard_t_user_id_d7f50f_idx'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('user', 'account', 'asset'), name='fundboard_holding_user_account_asset_uniq'),
        ),
        migrations.AddConstraint(
            model_name='pricehistory',
            constraint=models.UniqueConstraint(fields=('asset', 'date'), name='fundboard_pricehistory_asset_date_uniq'),
        ),
        migrations.AddField(
            model_name='cashflowrule',
            name='default_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FundBoard.account'),
        ),
        migrations.AddField(
            model_name='cashflowrule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leg',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='FundBoard.account'),
        ),
        migrations.AddField(
            model_name='leg',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='FundBoard.asset'),
        ),
        migrations.AddField(
            model_name='leg',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='FundBoard.transaction'),
        ),
        migrations.RunPython(migrate_legacy_data, noop_reverse),
        migrations.RemoveField(
            model_name='expense',
            name='account',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.RemoveField(
            model_name='income',
            name='account',
        ),
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_trx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='unit_price',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='avg_cost',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='volume',
        ),
        migrations.AddIndex(
            model_name='cashflowrule',
            index=models.Index(fields=['user', 'kind'], name='FundBoard_c_user_id_572580_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowrule',
            index=models.Index(fields=['user', 'next_due'], name='FundBoard_c_user_id_cbbea0_idx'),
        ),
        migrations.AddIndex(
            model_name='cashflowrule',
            index=models.Index(fields=['user', 'is_recurring'], name='FundBoard_c_user_id_b7571a_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashflowrule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('freq__isnull', True), ('freq_custom__isnull', True), ('is_recurring', False)), models.Q(('freq__isnull', False), ('is_recurring', True)), _connector='OR'), name='fundboard_cashflowrule_recurring_freq_consistency'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['transaction'], name='FundBoard_l_transac_5ddc00_idx'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['account', 'asset'], name='FundBoard_l_account_ee00aa_idx'),
        ),
        migrations.AddIndex(
            model_name='leg',
            index=models.Index(fields=['asset'], name='FundBoard_l_asset_i_f195b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='leg',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('adjustment_type__isnull', True), ('is_adjustment', False)), models.Q(('adjustment_type__isnull', False), ('is_adjustment', True)), _connector='OR'), name='fundboard_leg_adjustment_type_consistency'),
        ),
    ]
