# Generated by Django 4.2.3 on 2024-09-20 10:28

import GameBoard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('users', models.JSONField(default=dict)),
                ('game_grid', models.JSONField(default=list)),
                ('users_actions', models.JSONField(default=list)),
                ('ranking', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.JSONField(blank=True, default=list)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('versions', models.JSONField(blank=True, default=list)),
                ('tips', models.JSONField(blank=True, default=list)),
                ('cover', models.ImageField(default='GameBoard/Games/default.png', upload_to=GameBoard.models.get_upload_path)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categories', models.ManyToManyField(related_name='Game', to='GameBoard.category')),
            ],
        ),
        migrations.CreateModel(
            name='NavalBattleSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('users', models.JSONField(default=dict)),
                ('game_grid', models.JSONField(default=list)),
                ('calling_shot', models.JSONField(default=list)),
                ('ranking', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SkyJoSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('users', models.JSONField(default=dict)),
                ('scores', models.JSONField(default=dict)),
                ('ranking', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TicTacToeSave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('users', models.JSONField(default=dict)),
                ('game_grid', models.JSONField(default=list)),
                ('users_actions', models.JSONField(default=list)),
                ('ranking', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamesStats',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('game_version', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('game_stats', models.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameBoard.game')),
            ],
        ),
    ]
