# Generated by Django 4.2.3 on 2024-09-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DashBoard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('categories', models.ManyToManyField(related_name='jeux', to='GameBoard.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('profil', models.JSONField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en cours', 'En cours'), ('terminée', 'Terminée')], max_length=50)),
                ('jeu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameBoard.jeu')),
                ('tableau_de_bord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DashBoard.dashboard')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('tour', models.IntegerField()),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameBoard.joueur')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameBoard.partie')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePartie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('statistiques', models.JSONField(blank=True, null=True)),
                ('gagnant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameBoard.joueur')),
                ('partie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GameBoard.partie')),
            ],
        ),
    ]
