# Generated by Django 4.2.3 on 2024-09-18 20:07

import GameBoard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameBoard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='couverture',
            field=models.ImageField(default='GameBoard/jeux/default.webp', upload_to=GameBoard.models.get_upload_path),
        ),
    ]
