# Generated by Django 4.2.3 on 2024-09-18 20:17

import GameBoard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameBoard', '0002_jeu_couverture'),
    ]

    operations = [
        migrations.AddField(
            model_name='jeu',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='couverture',
            field=models.ImageField(default='GameBoard/jeux/default.png', upload_to=GameBoard.models.get_upload_path),
        ),
    ]
