# Generated by Django 4.2.3 on 2024-09-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameBoard', '0003_jeu_slug_alter_jeu_couverture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
