# Generated by Django 4.2.3 on 2024-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameBoard', '0005_alter_jeu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='couverture',
            field=models.ImageField(default='jeux/couvertures/default.png', upload_to='jeux/couvertures/'),
        ),
    ]
