# Generated by Django 4.2.3 on 2024-09-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameBoard', '0007_alter_jeu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
