# Generated by Django 4.2.3 on 2024-09-18 21:06

import GameBoard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameBoard', '0008_alter_jeu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='couverture',
            field=models.ImageField(default='GameBoard/jeux/default.png', upload_to=GameBoard.models.get_upload_path),
        ),
    ]
